### ISSUE TITLE
Slow performance caused by `getMediaGalleryImages` call?

### ISSUE THREAD

**Issue by jtomaszewski** [magesuite/product-tile#3]
We noticed that some of our category index page requests are way slower than the others, that is, they take ~2-4s instead of ~400ms.

After tracing them with Tideways, seems like much of the time is spent in the `MageSuite\ProductTile\Model\Tile\Fragment\Gallery\mages::getMediaGalleryImages` call:

![image](https://user-images.githubusercontent.com/1862580/101912677-5d4db500-3bc2-11eb-95aa-7a2c97e7878a.png)

Have you ever noticed that problem? Wondering whether that's normal or something that could be anyhow improved.

**Comment by diwipl** [comment]
Hi

I assume you're storing images on some non local storage system ?

Gallery is generating urls to thumbnails, and in native Magento that causes some is_file and file_exists to be executed. Both functions are slow when executed over non local storage.

**Comment by jtomaszewski** [comment]
> I assume you're storing images on some non local storage system ?

Well, kind-of, yeah. We have a shared disk volume, that is bound to several docker hosts, that is then bound to magento docker containers. 

Is that bad? I thought it's totally okay to have media folder on some remote directory ; I thought it's used only for download/uploading the assets, and not for e.g. generating HTML of product tiles. I saw you do similarly and use S3/EFS for media storage too? ( https://github.com/mageops/ansible-infrastructure )

Or do you rather keep all media files locally, at the machine that runs the magento app?

**Comment by diwipl** [comment]
We have completely custom solution that do not execute is_file, file_exist:

https://github.com/magesuite/lazy-resize

The drawbacks:
- it requires custom nginx/apache rewrite configuration
- some features (like watermarking for example) are not supported at all

**Comment by jtomaszewski** [comment]
Wow, that looks awesome, thanks! Was just wondering, there has to be an open source module somewhere for moving that resizing to be async. ;) Will try it out.

**Comment by diwipl** [comment]
Just FYI:
https://github.com/mageops/ansible-infrastructure/blob/4b4e708f08ca7182deac7fb67d760c13b9567fdd/roles/cs.nginx-magento/templates/magento_server_body.conf.j2#L94-L98

This is our rewrite for nginx.
